name: Super-Linter
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  super-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_WORKSPACE: ${{ github.workspace }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_C_SHARP: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
