name: Super-Linter
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  super-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # https://github.com/actions/checkout/issues/317#issuecomment-737107262
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_WORKSPACE: ${{ github.workspace }}
          VALIDATE_ALL_CODEBASE: true # Lint all files
          DEFAULT_BRANCH: main # Target branch
          VALIDATE_C_SHARP: true
          LINTER_RULES_PATH: Assets/Scripts
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
